# Header
menu:
  Home: /
  #Archives: /archives
  #Linux: /tags/Linux
  #Geant4&ROOT: /tags/Geant4-ROOT
  #Nuclearphysics: /tags/Nuclearphysics
  AboutMe: /about
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/wuhongyi"
  mail: "wuhongyi@qq.com"
  #weibo: "http://weibo.com/wuhongyi"
  rss: "#"
  #zhihu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: img/why.jpg
#是否开启分享
share: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
disqus_shortname: wuhongyi
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  PekingUniversity: http://http://www.pku.edu.cn/
  Geant4: http://geant4.cern.ch/
  ROOT: http://root.cern.ch/drupal/
  C++: http://www.cplusplus.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 人民，只有人民，才是创造世界历史的动力！
